backend:
  name: git-gateway
  branch: master

media_folder: 'static/img'
public_folder: 'img'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Spoiler', name: 'spoiler', widget: 'string', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', required: true }
      - { label: 'Keywords', name: 'keywords', widget: 'list', required: true }
      - { label: Body, name: body, widget: markdown }
